# Generated by Django 4.0.6 on 2022-08-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Super_Types',
            new_name='SuperType',
        ),
    ]
