# Generated by Django 4.0.6 on 2022-08-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supers',
            old_name='super_types',
            new_name='super_type',
        ),
    ]
